sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  username: <% ENV.fetch("DB_USER", "root") %>
  <% if ENV["DB_PASSWORD"] %>
  password: <% ENV["DB_PASSWORD"] %>
  <% end %>
  database: alchemy_devise_dummy_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  <% if ENV["DB_USER"] %>
  username: <% ENV["DB_USER"] %>
  <% end %>
  <% if ENV["DB_PASSWORD"] %>
  password: <% ENV["DB_PASSWORD"] %>
  <% end %>
  database: alchemy_devise_dummy_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV["DB"] || "sqlite" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
